// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default_routing.proto

#ifndef PROTOBUF_default_5frouting_2eproto__INCLUDED
#define PROTOBUF_default_5frouting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace routing {
class DefaultRouting;
class DefaultRoutingDefaultTypeInternal;
extern DefaultRoutingDefaultTypeInternal _DefaultRouting_default_instance_;
class DefaultRoutings;
class DefaultRoutingsDefaultTypeInternal;
extern DefaultRoutingsDefaultTypeInternal _DefaultRoutings_default_instance_;
}  // namespace routing
}  // namespace apollo

namespace apollo {
namespace routing {

namespace protobuf_default_5frouting_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_default_5frouting_2eproto

// ===================================================================

class DefaultRouting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.DefaultRouting) */ {
 public:
  DefaultRouting();
  virtual ~DefaultRouting();

  DefaultRouting(const DefaultRouting& from);

  inline DefaultRouting& operator=(const DefaultRouting& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DefaultRouting(DefaultRouting&& from) noexcept
    : DefaultRouting() {
    *this = ::std::move(from);
  }

  inline DefaultRouting& operator=(DefaultRouting&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DefaultRouting& default_instance();

  static inline const DefaultRouting* internal_default_instance() {
    return reinterpret_cast<const DefaultRouting*>(
               &_DefaultRouting_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DefaultRouting* other);
  friend void swap(DefaultRouting& a, DefaultRouting& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DefaultRouting* New() const PROTOBUF_FINAL { return New(NULL); }

  DefaultRouting* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DefaultRouting& from);
  void MergeFrom(const DefaultRouting& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DefaultRouting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.common.PointENU point = 2;
  int point_size() const;
  void clear_point();
  static const int kPointFieldNumber = 2;
  const ::apollo::common::PointENU& point(int index) const;
  ::apollo::common::PointENU* mutable_point(int index);
  ::apollo::common::PointENU* add_point();
  ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >*
      mutable_point();
  const ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >&
      point() const;

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:apollo.routing.DefaultRouting)
 private:
  void set_has_name();
  void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU > point_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  friend struct protobuf_default_5frouting_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DefaultRoutings : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.DefaultRoutings) */ {
 public:
  DefaultRoutings();
  virtual ~DefaultRoutings();

  DefaultRoutings(const DefaultRoutings& from);

  inline DefaultRoutings& operator=(const DefaultRoutings& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DefaultRoutings(DefaultRoutings&& from) noexcept
    : DefaultRoutings() {
    *this = ::std::move(from);
  }

  inline DefaultRoutings& operator=(DefaultRoutings&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DefaultRoutings& default_instance();

  static inline const DefaultRoutings* internal_default_instance() {
    return reinterpret_cast<const DefaultRoutings*>(
               &_DefaultRoutings_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(DefaultRoutings* other);
  friend void swap(DefaultRoutings& a, DefaultRoutings& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DefaultRoutings* New() const PROTOBUF_FINAL { return New(NULL); }

  DefaultRoutings* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DefaultRoutings& from);
  void MergeFrom(const DefaultRoutings& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DefaultRoutings* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.DefaultRouting defaultrouting = 1;
  int defaultrouting_size() const;
  void clear_defaultrouting();
  static const int kDefaultroutingFieldNumber = 1;
  const ::apollo::routing::DefaultRouting& defaultrouting(int index) const;
  ::apollo::routing::DefaultRouting* mutable_defaultrouting(int index);
  ::apollo::routing::DefaultRouting* add_defaultrouting();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >*
      mutable_defaultrouting();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >&
      defaultrouting() const;

  // @@protoc_insertion_point(class_scope:apollo.routing.DefaultRoutings)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting > defaultrouting_;
  friend struct protobuf_default_5frouting_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DefaultRouting

// optional string name = 1;
inline bool DefaultRouting::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DefaultRouting::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DefaultRouting::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DefaultRouting::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& DefaultRouting::name() const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRouting.name)
  return name_.GetNoArena();
}
inline void DefaultRouting::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.DefaultRouting.name)
}
#if LANG_CXX11
inline void DefaultRouting::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.DefaultRouting.name)
}
#endif
inline void DefaultRouting::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.DefaultRouting.name)
}
inline void DefaultRouting::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.DefaultRouting.name)
}
inline ::std::string* DefaultRouting::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRouting.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DefaultRouting::release_name() {
  // @@protoc_insertion_point(field_release:apollo.routing.DefaultRouting.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DefaultRouting::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.DefaultRouting.name)
}

// repeated .apollo.common.PointENU point = 2;
inline int DefaultRouting::point_size() const {
  return point_.size();
}
inline void DefaultRouting::clear_point() {
  point_.Clear();
}
inline const ::apollo::common::PointENU& DefaultRouting::point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRouting.point)
  return point_.Get(index);
}
inline ::apollo::common::PointENU* DefaultRouting::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRouting.point)
  return point_.Mutable(index);
}
inline ::apollo::common::PointENU* DefaultRouting::add_point() {
  // @@protoc_insertion_point(field_add:apollo.routing.DefaultRouting.point)
  return point_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >*
DefaultRouting::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.DefaultRouting.point)
  return &point_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >&
DefaultRouting::point() const {
  // @@protoc_insertion_point(field_list:apollo.routing.DefaultRouting.point)
  return point_;
}

// -------------------------------------------------------------------

// DefaultRoutings

// repeated .apollo.routing.DefaultRouting defaultrouting = 1;
inline int DefaultRoutings::defaultrouting_size() const {
  return defaultrouting_.size();
}
inline void DefaultRoutings::clear_defaultrouting() {
  defaultrouting_.Clear();
}
inline const ::apollo::routing::DefaultRouting& DefaultRoutings::defaultrouting(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Get(index);
}
inline ::apollo::routing::DefaultRouting* DefaultRoutings::mutable_defaultrouting(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Mutable(index);
}
inline ::apollo::routing::DefaultRouting* DefaultRoutings::add_defaultrouting() {
  // @@protoc_insertion_point(field_add:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >*
DefaultRoutings::mutable_defaultrouting() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.DefaultRoutings.defaultrouting)
  return &defaultrouting_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >&
DefaultRoutings::defaultrouting() const {
  // @@protoc_insertion_point(field_list:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace routing
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_default_5frouting_2eproto__INCLUDED
