// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default_routing.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "default_routing.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace routing {
class DefaultRoutingDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DefaultRouting>
     _instance;
} _DefaultRouting_default_instance_;
class DefaultRoutingsDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DefaultRoutings>
     _instance;
} _DefaultRoutings_default_instance_;

namespace protobuf_default_5frouting_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRouting, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRouting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRouting, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRouting, point_),
  0,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRoutings, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRoutings, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DefaultRoutings, defaultrouting_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(DefaultRouting)},
  { 9, 15, sizeof(DefaultRoutings)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_DefaultRouting_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DefaultRoutings_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "default_routing.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::apollo::common::protobuf_geometry_2eproto::InitDefaults();
  _DefaultRouting_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DefaultRouting_default_instance_);_DefaultRoutings_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DefaultRoutings_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025default_routing.proto\022\016apollo.routing\032"
      "\016geometry.proto\"F\n\016DefaultRouting\022\014\n\004nam"
      "e\030\001 \001(\t\022&\n\005point\030\002 \003(\0132\027.apollo.common.P"
      "ointENU\"I\n\017DefaultRoutings\0226\n\016defaultrou"
      "ting\030\001 \003(\0132\036.apollo.routing.DefaultRouti"
      "ng"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 202);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "default_routing.proto", &protobuf_RegisterTypes);
  ::apollo::common::protobuf_geometry_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_default_5frouting_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DefaultRouting::kNameFieldNumber;
const int DefaultRouting::kPointFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DefaultRouting::DefaultRouting()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_default_5frouting_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.routing.DefaultRouting)
}
DefaultRouting::DefaultRouting(const DefaultRouting& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      point_(from.point_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.routing.DefaultRouting)
}

void DefaultRouting::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DefaultRouting::~DefaultRouting() {
  // @@protoc_insertion_point(destructor:apollo.routing.DefaultRouting)
  SharedDtor();
}

void DefaultRouting::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DefaultRouting::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DefaultRouting::descriptor() {
  protobuf_default_5frouting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_default_5frouting_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DefaultRouting& DefaultRouting::default_instance() {
  protobuf_default_5frouting_2eproto::InitDefaults();
  return *internal_default_instance();
}

DefaultRouting* DefaultRouting::New(::google::protobuf::Arena* arena) const {
  DefaultRouting* n = new DefaultRouting;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DefaultRouting::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.routing.DefaultRouting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  point_.Clear();
  if (has_name()) {
    GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*name_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DefaultRouting::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.routing.DefaultRouting)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.routing.DefaultRouting.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .apollo.common.PointENU point = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_point()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.routing.DefaultRouting)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.routing.DefaultRouting)
  return false;
#undef DO_
}

void DefaultRouting::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.routing.DefaultRouting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.DefaultRouting.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .apollo.common.PointENU point = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->point_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->point(static_cast<int>(i)), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.routing.DefaultRouting)
}

::google::protobuf::uint8* DefaultRouting::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.routing.DefaultRouting)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.DefaultRouting.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .apollo.common.PointENU point = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->point_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->point(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.routing.DefaultRouting)
  return target;
}

size_t DefaultRouting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.routing.DefaultRouting)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .apollo.common.PointENU point = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->point_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->point(static_cast<int>(i)));
    }
  }

  // optional string name = 1;
  if (has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DefaultRouting::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.routing.DefaultRouting)
  GOOGLE_DCHECK_NE(&from, this);
  const DefaultRouting* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DefaultRouting>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.routing.DefaultRouting)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.routing.DefaultRouting)
    MergeFrom(*source);
  }
}

void DefaultRouting::MergeFrom(const DefaultRouting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.routing.DefaultRouting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  point_.MergeFrom(from.point_);
  if (from.has_name()) {
    set_has_name();
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void DefaultRouting::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.routing.DefaultRouting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DefaultRouting::CopyFrom(const DefaultRouting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.routing.DefaultRouting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DefaultRouting::IsInitialized() const {
  return true;
}

void DefaultRouting::Swap(DefaultRouting* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DefaultRouting::InternalSwap(DefaultRouting* other) {
  using std::swap;
  point_.InternalSwap(&other->point_);
  name_.Swap(&other->name_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DefaultRouting::GetMetadata() const {
  protobuf_default_5frouting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_default_5frouting_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DefaultRouting

// optional string name = 1;
bool DefaultRouting::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void DefaultRouting::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void DefaultRouting::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void DefaultRouting::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
const ::std::string& DefaultRouting::name() const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRouting.name)
  return name_.GetNoArena();
}
void DefaultRouting::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.DefaultRouting.name)
}
#if LANG_CXX11
void DefaultRouting::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.routing.DefaultRouting.name)
}
#endif
void DefaultRouting::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.DefaultRouting.name)
}
void DefaultRouting::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.DefaultRouting.name)
}
::std::string* DefaultRouting::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRouting.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DefaultRouting::release_name() {
  // @@protoc_insertion_point(field_release:apollo.routing.DefaultRouting.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DefaultRouting::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.DefaultRouting.name)
}

// repeated .apollo.common.PointENU point = 2;
int DefaultRouting::point_size() const {
  return point_.size();
}
void DefaultRouting::clear_point() {
  point_.Clear();
}
const ::apollo::common::PointENU& DefaultRouting::point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRouting.point)
  return point_.Get(index);
}
::apollo::common::PointENU* DefaultRouting::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRouting.point)
  return point_.Mutable(index);
}
::apollo::common::PointENU* DefaultRouting::add_point() {
  // @@protoc_insertion_point(field_add:apollo.routing.DefaultRouting.point)
  return point_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >*
DefaultRouting::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.DefaultRouting.point)
  return &point_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::common::PointENU >&
DefaultRouting::point() const {
  // @@protoc_insertion_point(field_list:apollo.routing.DefaultRouting.point)
  return point_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DefaultRoutings::kDefaultroutingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DefaultRoutings::DefaultRoutings()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_default_5frouting_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.routing.DefaultRoutings)
}
DefaultRoutings::DefaultRoutings(const DefaultRoutings& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      defaultrouting_(from.defaultrouting_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.routing.DefaultRoutings)
}

void DefaultRoutings::SharedCtor() {
  _cached_size_ = 0;
}

DefaultRoutings::~DefaultRoutings() {
  // @@protoc_insertion_point(destructor:apollo.routing.DefaultRoutings)
  SharedDtor();
}

void DefaultRoutings::SharedDtor() {
}

void DefaultRoutings::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DefaultRoutings::descriptor() {
  protobuf_default_5frouting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_default_5frouting_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DefaultRoutings& DefaultRoutings::default_instance() {
  protobuf_default_5frouting_2eproto::InitDefaults();
  return *internal_default_instance();
}

DefaultRoutings* DefaultRoutings::New(::google::protobuf::Arena* arena) const {
  DefaultRoutings* n = new DefaultRoutings;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DefaultRoutings::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.routing.DefaultRoutings)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  defaultrouting_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DefaultRoutings::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.routing.DefaultRoutings)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.routing.DefaultRouting defaultrouting = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_defaultrouting()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.routing.DefaultRoutings)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.routing.DefaultRoutings)
  return false;
#undef DO_
}

void DefaultRoutings::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.routing.DefaultRoutings)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.routing.DefaultRouting defaultrouting = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->defaultrouting_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->defaultrouting(static_cast<int>(i)), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.routing.DefaultRoutings)
}

::google::protobuf::uint8* DefaultRoutings::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.routing.DefaultRoutings)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.routing.DefaultRouting defaultrouting = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->defaultrouting_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->defaultrouting(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.routing.DefaultRoutings)
  return target;
}

size_t DefaultRoutings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.routing.DefaultRoutings)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .apollo.routing.DefaultRouting defaultrouting = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->defaultrouting_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->defaultrouting(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DefaultRoutings::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.routing.DefaultRoutings)
  GOOGLE_DCHECK_NE(&from, this);
  const DefaultRoutings* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DefaultRoutings>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.routing.DefaultRoutings)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.routing.DefaultRoutings)
    MergeFrom(*source);
  }
}

void DefaultRoutings::MergeFrom(const DefaultRoutings& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.routing.DefaultRoutings)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  defaultrouting_.MergeFrom(from.defaultrouting_);
}

void DefaultRoutings::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.routing.DefaultRoutings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DefaultRoutings::CopyFrom(const DefaultRoutings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.routing.DefaultRoutings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DefaultRoutings::IsInitialized() const {
  return true;
}

void DefaultRoutings::Swap(DefaultRoutings* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DefaultRoutings::InternalSwap(DefaultRoutings* other) {
  using std::swap;
  defaultrouting_.InternalSwap(&other->defaultrouting_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DefaultRoutings::GetMetadata() const {
  protobuf_default_5frouting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_default_5frouting_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DefaultRoutings

// repeated .apollo.routing.DefaultRouting defaultrouting = 1;
int DefaultRoutings::defaultrouting_size() const {
  return defaultrouting_.size();
}
void DefaultRoutings::clear_defaultrouting() {
  defaultrouting_.Clear();
}
const ::apollo::routing::DefaultRouting& DefaultRoutings::defaultrouting(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Get(index);
}
::apollo::routing::DefaultRouting* DefaultRoutings::mutable_defaultrouting(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Mutable(index);
}
::apollo::routing::DefaultRouting* DefaultRoutings::add_defaultrouting() {
  // @@protoc_insertion_point(field_add:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >*
DefaultRoutings::mutable_defaultrouting() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.DefaultRoutings.defaultrouting)
  return &defaultrouting_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::routing::DefaultRouting >&
DefaultRoutings::defaultrouting() const {
  // @@protoc_insertion_point(field_list:apollo.routing.DefaultRoutings.defaultrouting)
  return defaultrouting_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace routing
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
