// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navigator_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "navigator_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace relative_map {
class SampleParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SampleParam>
     _instance;
} _SampleParam_default_instance_;
class NavigatorConfigDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<NavigatorConfig>
     _instance;
} _NavigatorConfig_default_instance_;

namespace protobuf_navigator_5fconfig_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, straight_sample_interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, small_kappa_sample_interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, middle_kappa_sample_interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, large_kappa_sample_interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, small_kappa_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, middle_kappa_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SampleParam, large_kappa_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NavigatorConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NavigatorConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NavigatorConfig, enable_navigator_downsample_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NavigatorConfig, sample_param_),
  1,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, sizeof(SampleParam)},
  { 19, 26, sizeof(NavigatorConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SampleParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_NavigatorConfig_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "navigator_config.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SampleParam_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_SampleParam_default_instance_);_NavigatorConfig_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_NavigatorConfig_default_instance_);_NavigatorConfig_default_instance_._instance.get_mutable()->sample_param_ = const_cast< ::apollo::relative_map::SampleParam*>(
      ::apollo::relative_map::SampleParam::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026navigator_config.proto\022\023apollo.relativ"
      "e_map\"\203\002\n\013SampleParam\022#\n\030straight_sample"
      "_interval\030\001 \001(\001:\0013\022&\n\033small_kappa_sample"
      "_interval\030\002 \001(\001:\0011\022)\n\034middle_kappa_sampl"
      "e_interval\030\003 \001(\001:\0030.4\022(\n\033large_kappa_sam"
      "ple_interval\030\004 \001(\001:\0030.1\022\032\n\013small_kappa\030\005"
      " \001(\001:\0050.002\022\033\n\014middle_kappa\030\006 \001(\001:\0050.008"
      "\022\031\n\013large_kappa\030\007 \001(\001:\0040.02\"t\n\017Navigator"
      "Config\022)\n\033enable_navigator_downsample\030\001 "
      "\001(\010:\004true\0226\n\014sample_param\030\002 \001(\0132 .apollo"
      ".relative_map.SampleParam"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 425);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "navigator_config.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_navigator_5fconfig_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SampleParam::kStraightSampleIntervalFieldNumber;
const int SampleParam::kSmallKappaSampleIntervalFieldNumber;
const int SampleParam::kMiddleKappaSampleIntervalFieldNumber;
const int SampleParam::kLargeKappaSampleIntervalFieldNumber;
const int SampleParam::kSmallKappaFieldNumber;
const int SampleParam::kMiddleKappaFieldNumber;
const int SampleParam::kLargeKappaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SampleParam::SampleParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_navigator_5fconfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.relative_map.SampleParam)
}
SampleParam::SampleParam(const SampleParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&straight_sample_interval_, &from.straight_sample_interval_,
    static_cast<size_t>(reinterpret_cast<char*>(&large_kappa_) -
    reinterpret_cast<char*>(&straight_sample_interval_)) + sizeof(large_kappa_));
  // @@protoc_insertion_point(copy_constructor:apollo.relative_map.SampleParam)
}

void SampleParam::SharedCtor() {
  _cached_size_ = 0;
  straight_sample_interval_ = 3;
  small_kappa_sample_interval_ = 1;
  middle_kappa_sample_interval_ = 0.4;
  large_kappa_sample_interval_ = 0.1;
  small_kappa_ = 0.002;
  middle_kappa_ = 0.008;
  large_kappa_ = 0.02;
}

SampleParam::~SampleParam() {
  // @@protoc_insertion_point(destructor:apollo.relative_map.SampleParam)
  SharedDtor();
}

void SampleParam::SharedDtor() {
}

void SampleParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SampleParam::descriptor() {
  protobuf_navigator_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_navigator_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SampleParam& SampleParam::default_instance() {
  protobuf_navigator_5fconfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

SampleParam* SampleParam::New(::google::protobuf::Arena* arena) const {
  SampleParam* n = new SampleParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SampleParam::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.relative_map.SampleParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 127u) {
    straight_sample_interval_ = 3;
    small_kappa_sample_interval_ = 1;
    middle_kappa_sample_interval_ = 0.4;
    large_kappa_sample_interval_ = 0.1;
    small_kappa_ = 0.002;
    middle_kappa_ = 0.008;
    large_kappa_ = 0.02;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SampleParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.relative_map.SampleParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double straight_sample_interval = 1 [default = 3];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_straight_sample_interval();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &straight_sample_interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double small_kappa_sample_interval = 2 [default = 1];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_small_kappa_sample_interval();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &small_kappa_sample_interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double middle_kappa_sample_interval = 3 [default = 0.4];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_middle_kappa_sample_interval();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &middle_kappa_sample_interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double large_kappa_sample_interval = 4 [default = 0.1];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_large_kappa_sample_interval();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &large_kappa_sample_interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double small_kappa = 5 [default = 0.002];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          set_has_small_kappa();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &small_kappa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double middle_kappa = 6 [default = 0.008];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {
          set_has_middle_kappa();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &middle_kappa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double large_kappa = 7 [default = 0.02];
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {
          set_has_large_kappa();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &large_kappa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.relative_map.SampleParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.relative_map.SampleParam)
  return false;
#undef DO_
}

void SampleParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.relative_map.SampleParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double straight_sample_interval = 1 [default = 3];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->straight_sample_interval(), output);
  }

  // optional double small_kappa_sample_interval = 2 [default = 1];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->small_kappa_sample_interval(), output);
  }

  // optional double middle_kappa_sample_interval = 3 [default = 0.4];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->middle_kappa_sample_interval(), output);
  }

  // optional double large_kappa_sample_interval = 4 [default = 0.1];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->large_kappa_sample_interval(), output);
  }

  // optional double small_kappa = 5 [default = 0.002];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->small_kappa(), output);
  }

  // optional double middle_kappa = 6 [default = 0.008];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->middle_kappa(), output);
  }

  // optional double large_kappa = 7 [default = 0.02];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->large_kappa(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.relative_map.SampleParam)
}

::google::protobuf::uint8* SampleParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.relative_map.SampleParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double straight_sample_interval = 1 [default = 3];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->straight_sample_interval(), target);
  }

  // optional double small_kappa_sample_interval = 2 [default = 1];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->small_kappa_sample_interval(), target);
  }

  // optional double middle_kappa_sample_interval = 3 [default = 0.4];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->middle_kappa_sample_interval(), target);
  }

  // optional double large_kappa_sample_interval = 4 [default = 0.1];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->large_kappa_sample_interval(), target);
  }

  // optional double small_kappa = 5 [default = 0.002];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->small_kappa(), target);
  }

  // optional double middle_kappa = 6 [default = 0.008];
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->middle_kappa(), target);
  }

  // optional double large_kappa = 7 [default = 0.02];
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->large_kappa(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.relative_map.SampleParam)
  return target;
}

size_t SampleParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.relative_map.SampleParam)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 127u) {
    // optional double straight_sample_interval = 1 [default = 3];
    if (has_straight_sample_interval()) {
      total_size += 1 + 8;
    }

    // optional double small_kappa_sample_interval = 2 [default = 1];
    if (has_small_kappa_sample_interval()) {
      total_size += 1 + 8;
    }

    // optional double middle_kappa_sample_interval = 3 [default = 0.4];
    if (has_middle_kappa_sample_interval()) {
      total_size += 1 + 8;
    }

    // optional double large_kappa_sample_interval = 4 [default = 0.1];
    if (has_large_kappa_sample_interval()) {
      total_size += 1 + 8;
    }

    // optional double small_kappa = 5 [default = 0.002];
    if (has_small_kappa()) {
      total_size += 1 + 8;
    }

    // optional double middle_kappa = 6 [default = 0.008];
    if (has_middle_kappa()) {
      total_size += 1 + 8;
    }

    // optional double large_kappa = 7 [default = 0.02];
    if (has_large_kappa()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SampleParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.relative_map.SampleParam)
  GOOGLE_DCHECK_NE(&from, this);
  const SampleParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SampleParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.relative_map.SampleParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.relative_map.SampleParam)
    MergeFrom(*source);
  }
}

void SampleParam::MergeFrom(const SampleParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.relative_map.SampleParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      straight_sample_interval_ = from.straight_sample_interval_;
    }
    if (cached_has_bits & 0x00000002u) {
      small_kappa_sample_interval_ = from.small_kappa_sample_interval_;
    }
    if (cached_has_bits & 0x00000004u) {
      middle_kappa_sample_interval_ = from.middle_kappa_sample_interval_;
    }
    if (cached_has_bits & 0x00000008u) {
      large_kappa_sample_interval_ = from.large_kappa_sample_interval_;
    }
    if (cached_has_bits & 0x00000010u) {
      small_kappa_ = from.small_kappa_;
    }
    if (cached_has_bits & 0x00000020u) {
      middle_kappa_ = from.middle_kappa_;
    }
    if (cached_has_bits & 0x00000040u) {
      large_kappa_ = from.large_kappa_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SampleParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.relative_map.SampleParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SampleParam::CopyFrom(const SampleParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.relative_map.SampleParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SampleParam::IsInitialized() const {
  return true;
}

void SampleParam::Swap(SampleParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SampleParam::InternalSwap(SampleParam* other) {
  using std::swap;
  swap(straight_sample_interval_, other->straight_sample_interval_);
  swap(small_kappa_sample_interval_, other->small_kappa_sample_interval_);
  swap(middle_kappa_sample_interval_, other->middle_kappa_sample_interval_);
  swap(large_kappa_sample_interval_, other->large_kappa_sample_interval_);
  swap(small_kappa_, other->small_kappa_);
  swap(middle_kappa_, other->middle_kappa_);
  swap(large_kappa_, other->large_kappa_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SampleParam::GetMetadata() const {
  protobuf_navigator_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_navigator_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SampleParam

// optional double straight_sample_interval = 1 [default = 3];
bool SampleParam::has_straight_sample_interval() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SampleParam::set_has_straight_sample_interval() {
  _has_bits_[0] |= 0x00000001u;
}
void SampleParam::clear_has_straight_sample_interval() {
  _has_bits_[0] &= ~0x00000001u;
}
void SampleParam::clear_straight_sample_interval() {
  straight_sample_interval_ = 3;
  clear_has_straight_sample_interval();
}
double SampleParam::straight_sample_interval() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.straight_sample_interval)
  return straight_sample_interval_;
}
void SampleParam::set_straight_sample_interval(double value) {
  set_has_straight_sample_interval();
  straight_sample_interval_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.straight_sample_interval)
}

// optional double small_kappa_sample_interval = 2 [default = 1];
bool SampleParam::has_small_kappa_sample_interval() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SampleParam::set_has_small_kappa_sample_interval() {
  _has_bits_[0] |= 0x00000002u;
}
void SampleParam::clear_has_small_kappa_sample_interval() {
  _has_bits_[0] &= ~0x00000002u;
}
void SampleParam::clear_small_kappa_sample_interval() {
  small_kappa_sample_interval_ = 1;
  clear_has_small_kappa_sample_interval();
}
double SampleParam::small_kappa_sample_interval() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.small_kappa_sample_interval)
  return small_kappa_sample_interval_;
}
void SampleParam::set_small_kappa_sample_interval(double value) {
  set_has_small_kappa_sample_interval();
  small_kappa_sample_interval_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.small_kappa_sample_interval)
}

// optional double middle_kappa_sample_interval = 3 [default = 0.4];
bool SampleParam::has_middle_kappa_sample_interval() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void SampleParam::set_has_middle_kappa_sample_interval() {
  _has_bits_[0] |= 0x00000004u;
}
void SampleParam::clear_has_middle_kappa_sample_interval() {
  _has_bits_[0] &= ~0x00000004u;
}
void SampleParam::clear_middle_kappa_sample_interval() {
  middle_kappa_sample_interval_ = 0.4;
  clear_has_middle_kappa_sample_interval();
}
double SampleParam::middle_kappa_sample_interval() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.middle_kappa_sample_interval)
  return middle_kappa_sample_interval_;
}
void SampleParam::set_middle_kappa_sample_interval(double value) {
  set_has_middle_kappa_sample_interval();
  middle_kappa_sample_interval_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.middle_kappa_sample_interval)
}

// optional double large_kappa_sample_interval = 4 [default = 0.1];
bool SampleParam::has_large_kappa_sample_interval() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void SampleParam::set_has_large_kappa_sample_interval() {
  _has_bits_[0] |= 0x00000008u;
}
void SampleParam::clear_has_large_kappa_sample_interval() {
  _has_bits_[0] &= ~0x00000008u;
}
void SampleParam::clear_large_kappa_sample_interval() {
  large_kappa_sample_interval_ = 0.1;
  clear_has_large_kappa_sample_interval();
}
double SampleParam::large_kappa_sample_interval() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.large_kappa_sample_interval)
  return large_kappa_sample_interval_;
}
void SampleParam::set_large_kappa_sample_interval(double value) {
  set_has_large_kappa_sample_interval();
  large_kappa_sample_interval_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.large_kappa_sample_interval)
}

// optional double small_kappa = 5 [default = 0.002];
bool SampleParam::has_small_kappa() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void SampleParam::set_has_small_kappa() {
  _has_bits_[0] |= 0x00000010u;
}
void SampleParam::clear_has_small_kappa() {
  _has_bits_[0] &= ~0x00000010u;
}
void SampleParam::clear_small_kappa() {
  small_kappa_ = 0.002;
  clear_has_small_kappa();
}
double SampleParam::small_kappa() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.small_kappa)
  return small_kappa_;
}
void SampleParam::set_small_kappa(double value) {
  set_has_small_kappa();
  small_kappa_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.small_kappa)
}

// optional double middle_kappa = 6 [default = 0.008];
bool SampleParam::has_middle_kappa() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void SampleParam::set_has_middle_kappa() {
  _has_bits_[0] |= 0x00000020u;
}
void SampleParam::clear_has_middle_kappa() {
  _has_bits_[0] &= ~0x00000020u;
}
void SampleParam::clear_middle_kappa() {
  middle_kappa_ = 0.008;
  clear_has_middle_kappa();
}
double SampleParam::middle_kappa() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.middle_kappa)
  return middle_kappa_;
}
void SampleParam::set_middle_kappa(double value) {
  set_has_middle_kappa();
  middle_kappa_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.middle_kappa)
}

// optional double large_kappa = 7 [default = 0.02];
bool SampleParam::has_large_kappa() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void SampleParam::set_has_large_kappa() {
  _has_bits_[0] |= 0x00000040u;
}
void SampleParam::clear_has_large_kappa() {
  _has_bits_[0] &= ~0x00000040u;
}
void SampleParam::clear_large_kappa() {
  large_kappa_ = 0.02;
  clear_has_large_kappa();
}
double SampleParam::large_kappa() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.SampleParam.large_kappa)
  return large_kappa_;
}
void SampleParam::set_large_kappa(double value) {
  set_has_large_kappa();
  large_kappa_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.SampleParam.large_kappa)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NavigatorConfig::kEnableNavigatorDownsampleFieldNumber;
const int NavigatorConfig::kSampleParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NavigatorConfig::NavigatorConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_navigator_5fconfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.relative_map.NavigatorConfig)
}
NavigatorConfig::NavigatorConfig(const NavigatorConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_sample_param()) {
    sample_param_ = new ::apollo::relative_map::SampleParam(*from.sample_param_);
  } else {
    sample_param_ = NULL;
  }
  enable_navigator_downsample_ = from.enable_navigator_downsample_;
  // @@protoc_insertion_point(copy_constructor:apollo.relative_map.NavigatorConfig)
}

void NavigatorConfig::SharedCtor() {
  _cached_size_ = 0;
  sample_param_ = NULL;
  enable_navigator_downsample_ = true;
}

NavigatorConfig::~NavigatorConfig() {
  // @@protoc_insertion_point(destructor:apollo.relative_map.NavigatorConfig)
  SharedDtor();
}

void NavigatorConfig::SharedDtor() {
  if (this != internal_default_instance()) delete sample_param_;
}

void NavigatorConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NavigatorConfig::descriptor() {
  protobuf_navigator_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_navigator_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NavigatorConfig& NavigatorConfig::default_instance() {
  protobuf_navigator_5fconfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

NavigatorConfig* NavigatorConfig::New(::google::protobuf::Arena* arena) const {
  NavigatorConfig* n = new NavigatorConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NavigatorConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.relative_map.NavigatorConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(sample_param_ != NULL);
      sample_param_->::apollo::relative_map::SampleParam::Clear();
    }
    enable_navigator_downsample_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NavigatorConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.relative_map.NavigatorConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool enable_navigator_downsample = 1 [default = true];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_enable_navigator_downsample();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enable_navigator_downsample_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.relative_map.SampleParam sample_param = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sample_param()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.relative_map.NavigatorConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.relative_map.NavigatorConfig)
  return false;
#undef DO_
}

void NavigatorConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.relative_map.NavigatorConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool enable_navigator_downsample = 1 [default = true];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->enable_navigator_downsample(), output);
  }

  // optional .apollo.relative_map.SampleParam sample_param = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->sample_param_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.relative_map.NavigatorConfig)
}

::google::protobuf::uint8* NavigatorConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.relative_map.NavigatorConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool enable_navigator_downsample = 1 [default = true];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->enable_navigator_downsample(), target);
  }

  // optional .apollo.relative_map.SampleParam sample_param = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->sample_param_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.relative_map.NavigatorConfig)
  return target;
}

size_t NavigatorConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.relative_map.NavigatorConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional .apollo.relative_map.SampleParam sample_param = 2;
    if (has_sample_param()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->sample_param_);
    }

    // optional bool enable_navigator_downsample = 1 [default = true];
    if (has_enable_navigator_downsample()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NavigatorConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.relative_map.NavigatorConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const NavigatorConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NavigatorConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.relative_map.NavigatorConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.relative_map.NavigatorConfig)
    MergeFrom(*source);
  }
}

void NavigatorConfig::MergeFrom(const NavigatorConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.relative_map.NavigatorConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_sample_param()->::apollo::relative_map::SampleParam::MergeFrom(from.sample_param());
    }
    if (cached_has_bits & 0x00000002u) {
      enable_navigator_downsample_ = from.enable_navigator_downsample_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void NavigatorConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.relative_map.NavigatorConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NavigatorConfig::CopyFrom(const NavigatorConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.relative_map.NavigatorConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NavigatorConfig::IsInitialized() const {
  return true;
}

void NavigatorConfig::Swap(NavigatorConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NavigatorConfig::InternalSwap(NavigatorConfig* other) {
  using std::swap;
  swap(sample_param_, other->sample_param_);
  swap(enable_navigator_downsample_, other->enable_navigator_downsample_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NavigatorConfig::GetMetadata() const {
  protobuf_navigator_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_navigator_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NavigatorConfig

// optional bool enable_navigator_downsample = 1 [default = true];
bool NavigatorConfig::has_enable_navigator_downsample() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void NavigatorConfig::set_has_enable_navigator_downsample() {
  _has_bits_[0] |= 0x00000002u;
}
void NavigatorConfig::clear_has_enable_navigator_downsample() {
  _has_bits_[0] &= ~0x00000002u;
}
void NavigatorConfig::clear_enable_navigator_downsample() {
  enable_navigator_downsample_ = true;
  clear_has_enable_navigator_downsample();
}
bool NavigatorConfig::enable_navigator_downsample() const {
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigatorConfig.enable_navigator_downsample)
  return enable_navigator_downsample_;
}
void NavigatorConfig::set_enable_navigator_downsample(bool value) {
  set_has_enable_navigator_downsample();
  enable_navigator_downsample_ = value;
  // @@protoc_insertion_point(field_set:apollo.relative_map.NavigatorConfig.enable_navigator_downsample)
}

// optional .apollo.relative_map.SampleParam sample_param = 2;
bool NavigatorConfig::has_sample_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void NavigatorConfig::set_has_sample_param() {
  _has_bits_[0] |= 0x00000001u;
}
void NavigatorConfig::clear_has_sample_param() {
  _has_bits_[0] &= ~0x00000001u;
}
void NavigatorConfig::clear_sample_param() {
  if (sample_param_ != NULL) sample_param_->::apollo::relative_map::SampleParam::Clear();
  clear_has_sample_param();
}
const ::apollo::relative_map::SampleParam& NavigatorConfig::sample_param() const {
  const ::apollo::relative_map::SampleParam* p = sample_param_;
  // @@protoc_insertion_point(field_get:apollo.relative_map.NavigatorConfig.sample_param)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::relative_map::SampleParam*>(
      &::apollo::relative_map::_SampleParam_default_instance_);
}
::apollo::relative_map::SampleParam* NavigatorConfig::mutable_sample_param() {
  set_has_sample_param();
  if (sample_param_ == NULL) {
    sample_param_ = new ::apollo::relative_map::SampleParam;
  }
  // @@protoc_insertion_point(field_mutable:apollo.relative_map.NavigatorConfig.sample_param)
  return sample_param_;
}
::apollo::relative_map::SampleParam* NavigatorConfig::release_sample_param() {
  // @@protoc_insertion_point(field_release:apollo.relative_map.NavigatorConfig.sample_param)
  clear_has_sample_param();
  ::apollo::relative_map::SampleParam* temp = sample_param_;
  sample_param_ = NULL;
  return temp;
}
void NavigatorConfig::set_allocated_sample_param(::apollo::relative_map::SampleParam* sample_param) {
  delete sample_param_;
  sample_param_ = sample_param;
  if (sample_param) {
    set_has_sample_param();
  } else {
    clear_has_sample_param();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.relative_map.NavigatorConfig.sample_param)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace relative_map
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
